### PR TITLE
Neighbourhood updates

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/1990.

This PR:
- [x] Moves existing polygon geometries to points 
- [x] And for those existing polygons, adjusts the min_zoom as follows:
  - [x] 12 becomes 14
  - [x] 13 becomes 14.5
  - [x] 14 becomes 15
  - [x] 15 becomes 15.5
  - [x] 16 stays 16
- [x] And for existing points that fall into existing polygons, adjusts the min_zoom as follows:
  - [x] if the overlapping polygon has min_zoom 14, make point min_zoom 15 (one higher)
  - [x] if the overlapping polygon has min_zoom 15, make point min_zoom 16 (one higher)
  - [x] if the overlapping polygon has min_zoom 16, make point min_zoom 17 (one higher)
  - [x] if min_zoom is 18, keep as-is 
- [x] For all neighbourhoods, update max_zoom to 18
- [x] Review rural neighbourhoods with zooms 13, 14, 15
- [x] Add borough records in Tokyo

### CODE REVIEW

**Comment by stepps00** [comment]
This PR makes some fairly straight-forward `mz:max_zoom` changes, and converts polygons to points. There are some complex zoom changes, though:

For existing neighbourhoods polygons, the `mz:min_zoom` values are moved slightly:
-  12 becomes 14
-  13 becomes 14.5
-  14 becomes 15
-  15 becomes 15.5
-  16 stays 16

Then, neighbourhood points that fell in those neighbourhood polygons were adjusted with new `mz:min_zoom` values. 

Basically, the difference between the point's min_zoom and the min_zoom of the polygon that it falls within was calculated. If that difference was zero or lower, the difference was manually calculated to be 1. Then, that difference value was used to calculate the point's new min_zoom value.

This way, the zoom hierarchy stays in tact. This should be enough to smooth out and suppress some of the questionable zoom levels seen today, and doesn't require PIP work. Can merge once reviewed / approved.

**Comment by nvkelso** [comment]
Let's review heads up in QGIS this week before merging, please.

**Comment by stepps00** [comment]
We reviewed these changes, and overall things look as expected. Some of the neighbourhoods at zooms 13-15 do need adjusting, though.

For any neighbourhood point that falls outside of an existing neighbourhood polygon, let's tweak as follows:

- min_zoom of 13 is now 15
- min_zoom of 14 is now 15.2
- min_zoom of 14.5 is now 15.5

This keeps the zoom hierarchy in tact, but punts the labels back a bit, so they don't appear too early. We may also want to adjust borough-level records (or create them), but tbd. New commits incoming.

**Comment by stepps00** [comment]
@nvkelso I've made adjustments to the min_zoom values of rural neighbourhoods (details in the comment above), and I've added new borough records in Tokyo. The borough records are sourced from Mesoshapes, and essentially copies of existing county records already in WOF. The borough/county records are coterminous, and represent the Special Wards of Tokyo:

https://en.wikipedia.org/wiki/Special_wards_of_Tokyo

This should be all that is needed for this PR, so flagging for another review before merge.

**Comment by nvkelso** [comment]
Please adjust the XY location of the new borough points and set min_zoom more in the range of 9/10/11 for them. Then let's review again heads up in QGIS.

**Comment by stepps00** [comment]
The two most recent commits update the label centroids, centroid `src` value, and min_zooms for all borough records in Japan. This PR is ready for another review.

**Comment by stepps00** [comment]
Most recent commit moves borough min_zooms to 11.. QAing these changes in QGIS, 11 is more appropriate.

Here are a few screenshots of the changes..

**Boroughs, with label positions**
Screen Shot 2022-01-06 at 4 25 16 PM

**Neighbourhood label locations, present at zoom 14**
Screen Shot 2022-01-06 at 4 25 35 PM

**Neighbourhood label locations, present at zoom 15**
Screen Shot 2022-01-06 at 4 25 45 PM

**Neighbourhood label locations, present at zoom 16**
Screen Shot 2022-01-06 at 4 25 57 PM

**All label positions in the Tokyo urban center**
Screen Shot 2022-01-06 at 4 26 17 PM

**Review by nvkelso — APPROVED** [review]
LGTM, thanks

**Pull request merged**
